version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-maintenance:
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-maintenance:
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
